<a href="https://colab.research.google.com/github/Kominiarz97/simple_neural_network_numpy_v2/blob/master/simple_neural_network_numpy_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
np.random.seed(1)
syn0=2*np.random.random((3,4))-1
syn1=2*np.random.random((4,1))-1

In [ ]:
import numpy as np

X=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y_true=np.array([[0],[0],[1],[1]])

In [ ]:
def sigmoid(x,deriv=False):
  if (deriv is True):
    return (x*(1-x))
  else:
    return 1/(1+np.exp(-x))

In [ ]:
for epoch in range(50000):
  l0=X
  l1=sigmoid(np.dot(l0,syn0))
  l2=sigmoid(np.dot(l1,syn1))

  l2_error=y-l2
  if(epoch%10000==0):
    print(l2_error)
  l2_delta=l2_error*sigmoid(l2,deriv=True)
  l1_error=l2_delta.dot(syn1.T)
  l1_delta=l1_error*sigmoid(l1,deriv=True)


[[-0.00199093]
 [ 0.00248541]
 [ 0.002289  ]
 [-0.00294416]]
[[-0.00199093]
 [ 0.00248541]
 [ 0.002289  ]
 [-0.00294416]]
[[-0.00199093]
 [ 0.00248541]
 [ 0.002289  ]
 [-0.00294416]]
[[-0.00199093]
 [ 0.00248541]
 [ 0.002289  ]
 [-0.00294416]]
[[-0.00199093]
 [ 0.00248541]
 [ 0.002289  ]
 [-0.00294416]]


In [ ]:
print(l2)

[[0.00199093]
 [0.99751459]
 [0.997711  ]
 [0.00294416]]


In [ ]:
for i in range(4):
  if l2[i]<0.4:
    l2[i]=0
  elif l2[i]>=0.6:
    l2[i]=1
print(l2)

[[0.]
 [1.]
 [1.]
 [0.]]
